"""전역 상수 및 설정"""

# --- 화면/월드 ---
WORLD_WIDTH = 800
WORLD_HEIGHT = 600
FPS_PLAY = 60

# --- 플레이어 ---
PLAYER_SPEED = 4.0
PLAYER_DODGE_SPEED = 12.0
PLAYER_DODGE_DURATION = 10  # 프레임
PLAYER_DODGE_COOLDOWN = 45
PLAYER_ATTACK_RANGE = 48.0
PLAYER_ATTACK_COOLDOWN = 15
PLAYER_ATTACK_DAMAGE = 10
PLAYER_MAX_HP = 100
PLAYER_HITBOX_RADIUS = 12.0
PLAYER_INVINCIBLE_FRAMES = 20

# --- 보스 ---
BOSS_MAX_HP = 500
BOSS_SPEED = 2.5
BOSS_HITBOX_RADIUS = 24.0
PHASE_THRESHOLDS = [0.75, 0.50, 0.25]  # HP 비율 기준 페이즈 전환

# --- RL (Boss) ---
MAX_EPISODE_STEPS = 3000
OBSERVATION_DIM = 28
NUM_BOSS_ACTIONS = 16
ACTION_REPEAT = 5  # 보스 의사결정 주기 (프레임)

# --- RL (Player) ---
PLAYER_OBS_DIM = 32
PLAYER_ACTION_REPEAT = 3  # 플레이어 의사결정 주기 (보스보다 빠르게)
